"""new Tables added-entity_existence, address valiation

Revision ID: 7bbe0c504674
Revises: fb7ef924ff5f
Create Date: 2026-06-12 13:19:10.190711

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "7bbe0c504674"
down_revision = "fb7ef924ff5f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address_zone_master",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=True),
        sa.Column("geo_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("identifier", sa.String(length=255), nullable=True),
        sa.Column("identifier_type", sa.String(length=100), nullable=True),
        sa.Column("entity_type", sa.String(length=100), nullable=True),
        sa.Column("places", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("zone", sa.String(length=50), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("image_name", sa.String(length=255), nullable=True),
        sa.Column(
            "geocode_status",
            sa.Enum(
                "not_called",
                "failed",
                "passed",
                name="step_status_enum",
                schema="public",
            ),
            nullable=True,
        ),
        sa.Column(
            "places_status",
            sa.Enum(
                "not_called",
                "failed",
                "passed",
                name="step_status_enum",
                schema="public",
            ),
            nullable=True,
        ),
        sa.Column(
            "llm_status",
            sa.Enum(
                "not_called",
                "failed",
                "passed",
                name="step_status_enum",
                schema="public",
            ),
            nullable=True,
        ),
        sa.Column(
            "geocode_source",
            sa.Enum(
                "not_called",
                "google",
                "llm",
                name="geocode_source_enum",
                schema="public",
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("geo_id"),
    )
    op.create_table(
        "entity_existence",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kpi_area", sa.String(), nullable=False),
        sa.Column("kpi_code", sa.String(), nullable=False),
        sa.Column("kpi_flag", sa.Boolean(), nullable=False),
        sa.Column("kpi_value", sa.String(), nullable=True),
        sa.Column("kpi_details", sa.String(), nullable=True),
        sa.Column("ens_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("kpi_rating", sa.String(), nullable=True),
        sa.Column("kpi_definition", sa.String(), nullable=True),
        sa.Column("kpi_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ens_id", "session_id", "kpi_code", name="unique_ensid_session_kpient"
        ),
    )
    op.create_table(
        "google_ratings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("rating", sa.String(length=255), nullable=True),
        sa.Column("no_of_reviews", sa.Text(), nullable=True),
        sa.Column("reviews", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("identifier", sa.String(length=50), nullable=True),
        sa.Column("identifier_type", sa.String(length=50), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "external_supplier_data",
        sa.Column("google_image_name", sa.String(), nullable=True),
    )
    op.add_column(
        "external_supplier_data",
        sa.Column(
            "domain_validation", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.create_unique_constraint(None, "users_table", ["user_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users_table", type_="unique")
    op.drop_column("external_supplier_data", "domain_validation")
    op.drop_column("external_supplier_data", "google_image_name")
    op.drop_table("google_ratings")
    op.drop_table("entity_existence")
    op.drop_table("address_zone_master")
    # ### end Alembic commands ###
