"""change in address validation

Revision ID: 5e3fe456ef02
Revises: bde34e5e9d9d
Create Date: 2026-06-14 22:47:46.508744

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "5e3fe456ef02"
down_revision = "bde34e5e9d9d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "address_zone_master", sa.Column("bvd_id", sa.String(length=255), nullable=True)
    )
    op.alter_column(
        "address_zone_master",
        "geocode_status",
        existing_type=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        type_=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "places_status",
        existing_type=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        type_=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "llm_status",
        existing_type=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        type_=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "geocode_source",
        existing_type=postgresql.ENUM(
            "not_called", "google", "llm", name="geocode_source_enum"
        ),
        type_=sa.Enum(
            "not_called", "google", "llm", name="geocode_source_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.drop_column("address_zone_master", "identifier_type")
    op.drop_column("address_zone_master", "entity_type")
    op.drop_column("address_zone_master", "identifier")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "address_zone_master",
        sa.Column(
            "identifier", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "address_zone_master",
        sa.Column(
            "entity_type", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "address_zone_master",
        sa.Column(
            "identifier_type",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "address_zone_master",
        "geocode_source",
        existing_type=sa.Enum(
            "not_called", "google", "llm", name="geocode_source_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "google", "llm", name="geocode_source_enum"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "llm_status",
        existing_type=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "places_status",
        existing_type=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "geocode_status",
        existing_type=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        existing_nullable=True,
    )
    op.drop_column("address_zone_master", "bvd_id")
    # ### end Alembic commands ###
