"""new new column-onboarding date

Revision ID: 18ee9d3540c9
Revises: 7bbe0c504674
Create Date: 2026-06-14 01:27:11.879466

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "18ee9d3540c9"
down_revision = "7bbe0c504674"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orgdata")
    op.drop_table("matchbvdid")
    op.alter_column(
        "address_zone_master",
        "geocode_status",
        existing_type=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        type_=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "places_status",
        existing_type=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        type_=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "llm_status",
        existing_type=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        type_=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "geocode_source",
        existing_type=postgresql.ENUM(
            "not_called", "google", "llm", name="geocode_source_enum"
        ),
        type_=sa.Enum(
            "not_called", "google", "llm", name="geocode_source_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.add_column(
        "upload_supplier_master_data",
        sa.Column("unmodified_client_onboarding_date", sa.Date(), nullable=True),
    )
    op.add_column(
        "upload_supplier_master_data",
        sa.Column("uploaded_client_onboarding_date", sa.Date(), nullable=True),
    )
    op.add_column(
        "upload_supplier_master_data",
        sa.Column("client_onboarding_date", sa.Date(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upload_supplier_master_data", "client_onboarding_date")
    op.drop_column("upload_supplier_master_data", "uploaded_client_onboarding_date")
    op.drop_column("upload_supplier_master_data", "unmodified_client_onboarding_date")
    op.alter_column(
        "address_zone_master",
        "geocode_source",
        existing_type=sa.Enum(
            "not_called", "google", "llm", name="geocode_source_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "google", "llm", name="geocode_source_enum"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "llm_status",
        existing_type=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "places_status",
        existing_type=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "geocode_status",
        existing_type=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        existing_nullable=True,
    )
    op.create_table(
        "matchbvdid",
        sa.Column("bvdid", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "name_international",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "postcode", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column("city", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "country", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "phone_or_fax", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "email_or_website",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "national_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("state", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "address_type", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "ens_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("ens_id", name="matchbvdid_pkey"),
    )
    op.create_table(
        "orgdata",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "orgname", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "orgidentifier", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("bvdids", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="orgdata_pkey"),
        sa.UniqueConstraint("bvdids", name="orgdata_bvdids_key"),
        sa.UniqueConstraint("orgidentifier", name="orgdata_orgidentifier_key"),
    )
    # ### end Alembic commands ###
