"""change in google rating - bvd_id

Revision ID: 383e01455de3
Revises: 5e3fe456ef02
Create Date: 2026-06-15 09:28:58.995684

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "383e01455de3"
down_revision = "5e3fe456ef02"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "address_zone_master",
        "geocode_status",
        existing_type=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        type_=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "places_status",
        existing_type=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        type_=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "llm_status",
        existing_type=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        type_=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "geocode_source",
        existing_type=postgresql.ENUM(
            "not_called", "google", "llm", name="geocode_source_enum"
        ),
        type_=sa.Enum(
            "not_called", "google", "llm", name="geocode_source_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.add_column(
        "google_ratings", sa.Column("bvd_id", sa.String(length=100), nullable=True)
    )
    op.drop_column("google_ratings", "entity_type")
    op.drop_column("google_ratings", "identifier_type")
    op.drop_column("google_ratings", "identifier")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "google_ratings",
        sa.Column(
            "identifier", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "google_ratings",
        sa.Column(
            "identifier_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "google_ratings",
        sa.Column(
            "entity_type", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("google_ratings", "bvd_id")
    op.alter_column(
        "address_zone_master",
        "geocode_source",
        existing_type=sa.Enum(
            "not_called", "google", "llm", name="geocode_source_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "google", "llm", name="geocode_source_enum"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "llm_status",
        existing_type=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "places_status",
        existing_type=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "geocode_status",
        existing_type=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
