"""new new column-uploaded address

Revision ID: bde34e5e9d9d
Revises: 3b50bf21dfd2
Create Date: 2026-06-14 19:55:09.500606

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "bde34e5e9d9d"
down_revision = "3b50bf21dfd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "address_zone_master",
        "geocode_status",
        existing_type=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        type_=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "places_status",
        existing_type=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        type_=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "llm_status",
        existing_type=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        type_=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "geocode_source",
        existing_type=postgresql.ENUM(
            "not_called", "google", "llm", name="geocode_source_enum"
        ),
        type_=sa.Enum(
            "not_called", "google", "llm", name="geocode_source_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.add_column(
        "supplier_master_data", sa.Column("uploaded_address", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("supplier_master_data", "uploaded_address")
    op.alter_column(
        "address_zone_master",
        "geocode_source",
        existing_type=sa.Enum(
            "not_called", "google", "llm", name="geocode_source_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "google", "llm", name="geocode_source_enum"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "llm_status",
        existing_type=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "places_status",
        existing_type=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "geocode_status",
        existing_type=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
