"""new new column-onboarding date

Revision ID: 3b50bf21dfd2
Revises: 89c8fb688e99
Create Date: 2026-06-14 01:53:12.083919

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "3b50bf21dfd2"
down_revision = "89c8fb688e99"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "address_zone_master",
        "geocode_status",
        existing_type=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        type_=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "places_status",
        existing_type=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        type_=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "llm_status",
        existing_type=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        type_=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "geocode_source",
        existing_type=postgresql.ENUM(
            "not_called", "google", "llm", name="geocode_source_enum"
        ),
        type_=sa.Enum(
            "not_called", "google", "llm", name="geocode_source_enum", schema="public"
        ),
        existing_nullable=True,
    )
    op.add_column(
        "supplier_master_data",
        sa.Column("uploaded_client_onboarding_date", sa.Date(), nullable=True),
    )
    op.drop_column("supplier_master_data", "client_onboarding_date")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supplier_master_data",
        sa.Column(
            "client_onboarding_date", sa.DATE(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("supplier_master_data", "uploaded_client_onboarding_date")
    op.alter_column(
        "address_zone_master",
        "geocode_source",
        existing_type=sa.Enum(
            "not_called", "google", "llm", name="geocode_source_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "google", "llm", name="geocode_source_enum"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "llm_status",
        existing_type=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "places_status",
        existing_type=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "address_zone_master",
        "geocode_status",
        existing_type=sa.Enum(
            "not_called", "failed", "passed", name="step_status_enum", schema="public"
        ),
        type_=postgresql.ENUM(
            "not_called", "failed", "passed", name="step_status_enum"
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
